# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/peristocles/.local/lib/python3.9/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/peristocles/.local/lib/python3.9/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/peristocles/fun/compiler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/peristocles/fun/compiler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/peristocles/.local/lib/python3.9/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/peristocles/.local/lib/python3.9/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/peristocles/fun/compiler/CMakeFiles /home/peristocles/fun/compiler//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/peristocles/fun/compiler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named test_ast

# Build rule for target.
test_ast: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ast
.PHONY : test_ast

# fast build rule for target.
test_ast/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ast.dir/build.make CMakeFiles/test_ast.dir/build
.PHONY : test_ast/fast

#=============================================================================
# Target rules for targets named bou

# Build rule for target.
bou: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bou
.PHONY : bou

# fast build rule for target.
bou/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bou.dir/build.make CMakeFiles/bou.dir/build
.PHONY : bou/fast

arena.o: arena.cc.o
.PHONY : arena.o

# target to build an object file
arena.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ast.dir/build.make CMakeFiles/test_ast.dir/arena.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bou.dir/build.make CMakeFiles/bou.dir/arena.cc.o
.PHONY : arena.cc.o

arena.i: arena.cc.i
.PHONY : arena.i

# target to preprocess a source file
arena.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ast.dir/build.make CMakeFiles/test_ast.dir/arena.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bou.dir/build.make CMakeFiles/bou.dir/arena.cc.i
.PHONY : arena.cc.i

arena.s: arena.cc.s
.PHONY : arena.s

# target to generate assembly for a file
arena.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ast.dir/build.make CMakeFiles/test_ast.dir/arena.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bou.dir/build.make CMakeFiles/bou.dir/arena.cc.s
.PHONY : arena.cc.s

bou.o: bou.cc.o
.PHONY : bou.o

# target to build an object file
bou.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bou.dir/build.make CMakeFiles/bou.dir/bou.cc.o
.PHONY : bou.cc.o

bou.i: bou.cc.i
.PHONY : bou.i

# target to preprocess a source file
bou.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bou.dir/build.make CMakeFiles/bou.dir/bou.cc.i
.PHONY : bou.cc.i

bou.s: bou.cc.s
.PHONY : bou.s

# target to generate assembly for a file
bou.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bou.dir/build.make CMakeFiles/bou.dir/bou.cc.s
.PHONY : bou.cc.s

compiler.o: compiler.cc.o
.PHONY : compiler.o

# target to build an object file
compiler.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bou.dir/build.make CMakeFiles/bou.dir/compiler.cc.o
.PHONY : compiler.cc.o

compiler.i: compiler.cc.i
.PHONY : compiler.i

# target to preprocess a source file
compiler.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bou.dir/build.make CMakeFiles/bou.dir/compiler.cc.i
.PHONY : compiler.cc.i

compiler.s: compiler.cc.s
.PHONY : compiler.s

# target to generate assembly for a file
compiler.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bou.dir/build.make CMakeFiles/bou.dir/compiler.cc.s
.PHONY : compiler.cc.s

darray.o: darray.cc.o
.PHONY : darray.o

# target to build an object file
darray.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/darray.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ast.dir/build.make CMakeFiles/test_ast.dir/darray.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bou.dir/build.make CMakeFiles/bou.dir/darray.cc.o
.PHONY : darray.cc.o

darray.i: darray.cc.i
.PHONY : darray.i

# target to preprocess a source file
darray.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/darray.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ast.dir/build.make CMakeFiles/test_ast.dir/darray.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bou.dir/build.make CMakeFiles/bou.dir/darray.cc.i
.PHONY : darray.cc.i

darray.s: darray.cc.s
.PHONY : darray.s

# target to generate assembly for a file
darray.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/darray.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ast.dir/build.make CMakeFiles/test_ast.dir/darray.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bou.dir/build.make CMakeFiles/bou.dir/darray.cc.s
.PHONY : darray.cc.s

debug.o: debug.cc.o
.PHONY : debug.o

# target to build an object file
debug.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ast.dir/build.make CMakeFiles/test_ast.dir/debug.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bou.dir/build.make CMakeFiles/bou.dir/debug.cc.o
.PHONY : debug.cc.o

debug.i: debug.cc.i
.PHONY : debug.i

# target to preprocess a source file
debug.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ast.dir/build.make CMakeFiles/test_ast.dir/debug.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bou.dir/build.make CMakeFiles/bou.dir/debug.cc.i
.PHONY : debug.cc.i

debug.s: debug.cc.s
.PHONY : debug.s

# target to generate assembly for a file
debug.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ast.dir/build.make CMakeFiles/test_ast.dir/debug.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bou.dir/build.make CMakeFiles/bou.dir/debug.cc.s
.PHONY : debug.cc.s

elf.o: elf.cc.o
.PHONY : elf.o

# target to build an object file
elf.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bou.dir/build.make CMakeFiles/bou.dir/elf.cc.o
.PHONY : elf.cc.o

elf.i: elf.cc.i
.PHONY : elf.i

# target to preprocess a source file
elf.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bou.dir/build.make CMakeFiles/bou.dir/elf.cc.i
.PHONY : elf.cc.i

elf.s: elf.cc.s
.PHONY : elf.s

# target to generate assembly for a file
elf.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bou.dir/build.make CMakeFiles/bou.dir/elf.cc.s
.PHONY : elf.cc.s

parser.o: parser.cc.o
.PHONY : parser.o

# target to build an object file
parser.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ast.dir/build.make CMakeFiles/test_ast.dir/parser.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bou.dir/build.make CMakeFiles/bou.dir/parser.cc.o
.PHONY : parser.cc.o

parser.i: parser.cc.i
.PHONY : parser.i

# target to preprocess a source file
parser.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ast.dir/build.make CMakeFiles/test_ast.dir/parser.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bou.dir/build.make CMakeFiles/bou.dir/parser.cc.i
.PHONY : parser.cc.i

parser.s: parser.cc.s
.PHONY : parser.s

# target to generate assembly for a file
parser.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ast.dir/build.make CMakeFiles/test_ast.dir/parser.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bou.dir/build.make CMakeFiles/bou.dir/parser.cc.s
.PHONY : parser.cc.s

scanner.o: scanner.cc.o
.PHONY : scanner.o

# target to build an object file
scanner.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bou.dir/build.make CMakeFiles/bou.dir/scanner.cc.o
.PHONY : scanner.cc.o

scanner.i: scanner.cc.i
.PHONY : scanner.i

# target to preprocess a source file
scanner.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bou.dir/build.make CMakeFiles/bou.dir/scanner.cc.i
.PHONY : scanner.cc.i

scanner.s: scanner.cc.s
.PHONY : scanner.s

# target to generate assembly for a file
scanner.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bou.dir/build.make CMakeFiles/bou.dir/scanner.cc.s
.PHONY : scanner.cc.s

test_ast.o: test_ast.cc.o
.PHONY : test_ast.o

# target to build an object file
test_ast.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ast.dir/build.make CMakeFiles/test_ast.dir/test_ast.cc.o
.PHONY : test_ast.cc.o

test_ast.i: test_ast.cc.i
.PHONY : test_ast.i

# target to preprocess a source file
test_ast.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ast.dir/build.make CMakeFiles/test_ast.dir/test_ast.cc.i
.PHONY : test_ast.cc.i

test_ast.s: test_ast.cc.s
.PHONY : test_ast.s

# target to generate assembly for a file
test_ast.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ast.dir/build.make CMakeFiles/test_ast.dir/test_ast.cc.s
.PHONY : test_ast.cc.s

test_darray.o: test_darray.cc.o
.PHONY : test_darray.o

# target to build an object file
test_darray.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test_darray.cc.o
.PHONY : test_darray.cc.o

test_darray.i: test_darray.cc.i
.PHONY : test_darray.i

# target to preprocess a source file
test_darray.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test_darray.cc.i
.PHONY : test_darray.cc.i

test_darray.s: test_darray.cc.s
.PHONY : test_darray.s

# target to generate assembly for a file
test_darray.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test_darray.cc.s
.PHONY : test_darray.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bou"
	@echo "... test"
	@echo "... test_ast"
	@echo "... arena.o"
	@echo "... arena.i"
	@echo "... arena.s"
	@echo "... bou.o"
	@echo "... bou.i"
	@echo "... bou.s"
	@echo "... compiler.o"
	@echo "... compiler.i"
	@echo "... compiler.s"
	@echo "... darray.o"
	@echo "... darray.i"
	@echo "... darray.s"
	@echo "... debug.o"
	@echo "... debug.i"
	@echo "... debug.s"
	@echo "... elf.o"
	@echo "... elf.i"
	@echo "... elf.s"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
	@echo "... scanner.o"
	@echo "... scanner.i"
	@echo "... scanner.s"
	@echo "... test_ast.o"
	@echo "... test_ast.i"
	@echo "... test_ast.s"
	@echo "... test_darray.o"
	@echo "... test_darray.i"
	@echo "... test_darray.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

